function spec = algorithmSpec()
%ALGORITHMSPEC Return the single public PGCIN-WHCL algorithm identity.

spec = struct( ...
    'algorithm', 'PGCIN-WHCL', ...
    'roundDomain', uint8('pgcin-whcl-round'), ...
    'sessionDomain', uint8('pgcin-whcl-session'), ...
    'sivDomain', uint8('pgcin-whcl-siv'), ...
    'defaultNonce', zeros(1, 16, 'uint8'));
end
