function plain = decryptImage(cipher, cfg, meta)
%DECRYPTIMAGE Decrypt a PGCIN-WHCL ciphertext and remove padding.

validateattributes(cipher, {'uint8'}, {'nonempty'});
required = {'originalSize', 'paddedSize', 'tileSize', 'syntheticIV', ...
    'algorithm', 'publicNonce', 'roundKeyDomain', 'sivDomain', ...
    'controlLayer', 'sessionPeriod', 'sessionOrigin', ...
    'sessionStride', 'stageCount', 'chaosDriver', 'chaosExtraction', ...
    'chaosPrecision'};
assert(isstruct(meta) && all(isfield(meta, required)), ...
    'PGCIN-WHCL metadata is incomplete.');
validateattributes(meta.originalSize, {'numeric'}, ...
    {'vector', 'numel', 3, 'integer', 'positive'});
validateattributes(meta.paddedSize, {'numeric'}, ...
    {'vector', 'numel', 3, 'integer', 'positive'});
assert(isequal(size(cipher), meta.paddedSize), ...
    'Cipher size does not match metadata.');
assert(meta.originalSize(3) == 3 && meta.paddedSize(3) == 3 ...
    && all(meta.originalSize <= meta.paddedSize), ...
    'Image-size metadata is invalid.');
assert(cfg.tileSize == meta.tileSize, 'Tile-size mismatch.');
spec = pgcinwhcl.algorithmSpec();
assert(strcmp(meta.algorithm, spec.algorithm), ...
    'PGCIN-WHCL metadata algorithm identity is invalid.');
validateattributes(meta.publicNonce, {'uint8'}, {'vector', 'numel', 16});
assert(isequal(meta.roundKeyDomain(:).', spec.roundDomain), ...
    'PGCIN-WHCL round-key domain metadata is inconsistent.');
assert(isequal(meta.sivDomain(:).', spec.sivDomain), ...
    'PGCIN-WHCL SIV domain metadata is inconsistent.');
assert(strcmp(meta.controlLayer, cfg.controlLayer), ...
    'Control-layer metadata mismatch.');
assert(strcmp(cfg.chaosDriver, meta.chaosDriver), ...
    'Chaos-driver mismatch.');
assert(strcmp(cfg.chaosExtraction, meta.chaosExtraction), ...
    'Chaos-extraction mismatch.');
assert(strcmpi(meta.chaosPrecision, 'double'), ...
    'Chaos-precision metadata mismatch.');
runtimeConfig = pgcinwhcl.runtimeConfigFromMetadata(cfg, meta);
tileCount = (meta.paddedSize(1) / cfg.tileSize) ...
    * (meta.paddedSize(2) / cfg.tileSize);
session = pgcinwhcl.deriveSession(runtimeConfig, meta.syntheticIV, tileCount);
assert(session.origin == uint64(meta.sessionOrigin) ...
    && session.stride == uint64(meta.sessionStride), ...
    'Session metadata does not reproduce the encryption session.');
assert(session.period == uint64(meta.sessionPeriod) ...
    && session.stageCount == uint8(meta.stageCount), ...
    'Session period or stage-count metadata mismatch.');
padded = pgcinwhcl.processImage(cipher, runtimeConfig, session, false);
plain = padded(1:meta.originalSize(1), 1:meta.originalSize(2), :);
end
