function [cipher, meta, traceData] = encryptImage(plain, cfg)
%ENCRYPTIMAGE Encrypt an RGB uint8 image with PGCIN-WHCL.

validateattributes(plain, {'uint8'}, {'nonempty'});
assert(ndims(plain) == 3 && size(plain, 3) == 3, ...
    'Input must be an RGB uint8 image.');
[encryptionConfig, publicNonce, nonceSource] = ...
    pgcinwhcl.resolveEncryptionConfig(cfg);
spec = pgcinwhcl.algorithmSpec();
originalSize = size(plain);
paddedHeight = ceil(originalSize(1) / cfg.tileSize) * cfg.tileSize;
paddedWidth = ceil(originalSize(2) / cfg.tileSize) * cfg.tileSize;
padded = zeros(paddedHeight, paddedWidth, 3, 'uint8');
padded(1:originalSize(1), 1:originalSize(2), :) = plain;
syntheticIV = pgcinwhcl.deriveSyntheticIV(plain, encryptionConfig);
runtimeConfig = pgcinwhcl.applySyntheticIV(encryptionConfig, syntheticIV);
tileCount = (paddedHeight / cfg.tileSize) * (paddedWidth / cfg.tileSize);
session = pgcinwhcl.deriveSession(runtimeConfig, syntheticIV, tileCount);
if nargout > 2
    [cipher, stageImages, addressOutput] = pgcinwhcl.processImage( ...
        padded, runtimeConfig, session, true);
else
    cipher = pgcinwhcl.processImage(padded, runtimeConfig, session, true);
end
meta = struct('originalSize', originalSize, 'paddedSize', size(padded), ...
    'tileSize', cfg.tileSize, 'publicNonce', publicNonce, ...
    'nonceSource', nonceSource, ...
    'syntheticIV', syntheticIV, 'algorithm', spec.algorithm, ...
    'roundKeyDomain', spec.roundDomain, ...
    'sivDomain', spec.sivDomain, ...
    'controlLayer', cfg.controlLayer, ...
    'sessionPeriod', session.period, 'sessionOrigin', session.origin, ...
    'sessionStride', session.stride, 'stageCount', session.stageCount, ...
    'chaosDriver', encryptionConfig.chaosDriver, ...
    'chaosExtraction', encryptionConfig.chaosExtraction, ...
    'chaosPrecision', 'double');
if nargout > 2
    traceData = struct('plain', padded, 'permutation', addressOutput, ...
        'stageStates', {stageImages});
else
    traceData = struct();
end
end
